checks:
    php: true

filter:
    excluded_paths:
        - tests/*
        - vendor/*
        - bin/*

build:
    environment:
        php:
            version: 5.6
    tests:
        override:
            -
                command: 'bin/phpunit --coverage-clover=cover'
                coverage:
                    file: 'cover'
                    format: 'php-clover'